using System;
using System.Collections.Generic;
using System.Text;

namespace Rezolver.Options
{
    /// <summary>
    /// Controls whether enumerables which are automatically generated by the container when the <see cref="Configuration.InjectEnumerables"/> configuration
    /// is used and enabled are evaluated lazily or eagerly.
    /// 
    /// A lazily evaluated enumerable will generate new instances (if not otherwise controlled by singleton/scoped lifetimes) every time it is enumerated.
    /// 
    /// Eagerly evaluted enumerables do not.
    /// </summary>
    public class LazyEnumerables : ContainerOption<bool>
    {
        public static LazyEnumerables Default { get; } = true;

        public static implicit operator LazyEnumerables(bool value)
        {
            return new LazyEnumerables() { Value = value };
        }
    }
}
