//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezolver.Tests.ConfigurationTests.Json {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonTestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonTestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rezolver.Tests.ConfigurationTests.Json.JsonTestResources", typeof(JsonTestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;assemblies&quot;: [
        ///		&quot;Rezolver.Tests&quot;
        ///	],
        ///	&quot;using&quot;: [ 
        ///		
        ///	],
        ///	&quot;rezolve&quot;: [
        ///		{ &quot;System.Int32&quot;: 10 },
        ///		{ &quot;Rezolver.Tests.ConfigurationTests.RequiresInt&quot;: { &quot;$construct&quot;: &quot;$self&quot; } },
        ///		{ &quot;Rezolver.Tests.ConfigurationTests.IRequiresInt&quot;: { &quot;$construct&quot;: &quot;Rezolver.Tests.ConfigurationTests.RequiresInt&quot; } },
        ///		{
        ///			&quot;type&quot;: { &quot;name&quot;: &quot;System.Collections.Generic.IEnumerable&quot;, &quot;args&quot;: [ &quot;System.Int32&quot; ] },
        ///			&quot;value&quot;: [ 1, 2, 3 ]
        ///		},
        ///		{
        ///			&quot;types&quot;: [ &quot;System.Object&quot;, &quot;System.String&quot; ],
        ///			&quot;valu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;assemblies&quot;: [
        ///		&quot;Rezolver.Tests&quot;
        ///	],
        ///	&quot;using&quot;: [ 
        ///		
        ///	],
        ///	&quot;rezolve&quot;: [
        ///		{ &quot;System.Int32&quot;: 10 },
        ///		{ &quot;Rezolver.Tests.ConfigurationTests.RequiresInt&quot;: { &quot;$construct&quot;: &quot;$self&quot; } },
        ///		{ &quot;Rezolver.Tests.ConfigurationTests.IRequiresInt&quot;: { &quot;$construct&quot;: &quot;Rezolver.Tests.ConfigurationTests.RequiresInt&quot; } },
        ///		{
        ///			&quot;type&quot;: { &quot;name&quot;: &quot;System.Collections.Generic.IEnumerable&quot;, &quot;args&quot;: [ &quot;System.Int32&quot; ] },
        ///			&quot;value&quot;: [ 1, 2, 3 ]
        ///		},
        ///		{
        ///			&quot;types&quot;: [ &quot;System.Object&quot;, &quot;System.String&quot; ],
        ///			&quot;valu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
    }
}
